In [1]:
import torch
import torch.nn as nn

In [2]:
# Defina a semente aleatória para PyTorch
torch.manual_seed(42)

# Se você estiver usando GPU, também é recomendável definir a semente aleatória do CUDA
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(42)

# Além disso, se você estiver usando bibliotecas que dependem do numpy, como Scikit-learn,
# você também deve definir a semente aleatória do numpy para garantir a reprodutibilidade.
# np.random.seed(42)

In [22]:
N = 4
L = 2
H_in = 1
H_out = 2
N_layers = 1

In [23]:
input = torch.rand((N, L, H_in))

In [24]:
input_batchfirst_true = input

In [25]:
input_batchfirst_false = input.permute(1,0,2)

In [26]:
input_batchfirst_true

tensor([[[0.5547],
         [0.3423]],

        [[0.6343],
         [0.3644]],

        [[0.7104],
         [0.9464]],

        [[0.7890],
         [0.2814]]])

In [27]:
input_batchfirst_false

tensor([[[0.5547],
         [0.6343],
         [0.7104],
         [0.7890]],

        [[0.3423],
         [0.3644],
         [0.9464],
         [0.2814]]])

In [28]:
batch_first = True
rnn_layer = nn.RNN(H_in, H_out, N_layers, batch_first=batch_first)

In [35]:
h0 = torch.zeros(N_layers, N,H_out)

In [36]:
out, h_i = rnn_layer(input_batchfirst_true, h0)
print(f'out:\n{out}\nh_i:\n{h_i}')

out:
tensor([[[-0.1118,  0.7367],
         [-0.5055,  0.6603]],

        [[-0.0796,  0.7413],
         [-0.4915,  0.6483]],

        [[-0.0487,  0.7456],
         [-0.2832,  0.6768]],

        [[-0.0166,  0.7500],
         [-0.5028,  0.6141]]], grad_fn=<TransposeBackward1>)
h_i:
tensor([[[-0.5055,  0.6603],
         [-0.4915,  0.6483],
         [-0.2832,  0.6768],
         [-0.5028,  0.6141]]], grad_fn=<StackBackward0>)


In [37]:
out, h_i = rnn_layer(input_batchfirst_true)
print(f'out:\n{out}\nh_i:\n{h_i}')

out:
tensor([[[-0.1118,  0.7367],
         [-0.5055,  0.6603]],

        [[-0.0796,  0.7413],
         [-0.4915,  0.6483]],

        [[-0.0487,  0.7456],
         [-0.2832,  0.6768]],

        [[-0.0166,  0.7500],
         [-0.5028,  0.6141]]], grad_fn=<TransposeBackward1>)
h_i:
tensor([[[-0.5055,  0.6603],
         [-0.4915,  0.6483],
         [-0.2832,  0.6768],
         [-0.5028,  0.6141]]], grad_fn=<StackBackward0>)


In [38]:
batch_first = False
rnn_layer = nn.RNN(H_in, H_out, N_layers, batch_first=batch_first)

In [39]:
out, h_i = rnn_layer(input_batchfirst_false)
print(f'out:\n{out}\nh_i:\n{h_i}')

out:
tensor([[[ 0.5070, -0.3779],
         [ 0.5202, -0.3788],
         [ 0.5325, -0.3796],
         [ 0.5449, -0.3804]],

        [[ 0.7538, -0.1878],
         [ 0.7592, -0.1871],
         [ 0.8116, -0.1931],
         [ 0.7575, -0.1843]]], grad_fn=<StackBackward0>)
h_i:
tensor([[[ 0.7538, -0.1878],
         [ 0.7592, -0.1871],
         [ 0.8116, -0.1931],
         [ 0.7575, -0.1843]]], grad_fn=<StackBackward0>)


In [40]:
input_batchfirst_false.shape

torch.Size([2, 4, 1])

In [21]:
input_batchfirst_true

tensor([[[0.8823],
         [0.9150]],

        [[0.3829],
         [0.9593]],

        [[0.3904],
         [0.6009]],

        [[0.2566],
         [0.7936]]])