In [3]:
import numpy as np
from typing import TypeAlias

In [4]:
Array: TypeAlias = np.ndarray

In [27]:
logits = np.array([[5.2, 3.1, 0.72, -2], [5.2, 3.1, 0.72, 0]])
logits

array([[ 5.2 ,  3.1 ,  0.72, -2.  ],
       [ 5.2 ,  3.1 ,  0.72,  0.  ]])

In [28]:
def softmax(x: Array, axis: int = -1) -> Array:
    x_shifted = x - np.max(x, axis=axis, keepdims=True)
    exp_x = np.exp(x_shifted)
    return exp_x / np.sum(exp_x, axis=axis, keepdims=True)

In [29]:
np.sum(softmax(logits), axis=-1, keepdims=True)

array([[1.],
       [1.]])

In [30]:
import jax.nn as jnn

jnn.softmax(logits)

Array([[8.8141721e-01, 1.0793521e-01, 9.9894702e-03, 6.5805373e-04],
       [8.7772697e-01, 1.0748332e-01, 9.9476473e-03, 4.8420383e-03]],      dtype=float32)

In [31]:
jnn.gelu(logits)

Array([[ 5.2       ,  3.0973732 ,  0.55019045, -0.04540235],
       [ 5.2       ,  3.0973732 ,  0.55019045,  0.        ]],      dtype=float32)

In [32]:
jnn.relu(logits)

Array([[5.2 , 3.1 , 0.72, 0.  ],
       [5.2 , 3.1 , 0.72, 0.  ]], dtype=float32)

In [33]:
jnn.tanh(logits)

Array([[ 0.99993914,  0.9959493 ,  0.6169093 , -0.9640276 ],
       [ 0.99993914,  0.9959493 ,  0.6169093 ,  0.        ]],      dtype=float32)

In [34]:
jnn.swish(logits)

Array([[ 5.171471  ,  2.9663675 ,  0.48427707, -0.23840584],
       [ 5.171471  ,  2.9663675 ,  0.48427707,  0.        ]],      dtype=float32)

In [35]:
jnn.leaky_relu(logits)

Array([[ 5.2 ,  3.1 ,  0.72, -0.02],
       [ 5.2 ,  3.1 ,  0.72,  0.  ]], dtype=float32)

In [38]:
jnn.dot_product_attention(logits, logits * 3, logits * 4)

Array([[20.8 , 12.4 ,  2.88, -8.  ],
       [20.8 , 12.4 ,  2.88,  0.  ]], dtype=float32)

In [39]:
from jax import lax

In [ ]:
lax.